version: '3'
services:
  docker-tester:
    image: api-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/mount/generated/:/mount/generated/
    ports:
      - 3000:3000 